tests:
  - name: "cmp"
    description: "Implement `cmp.Min` and `cmp.Max`"
    topic: "00-introduction"
    score: 0
  - name: "primes"
    description: "Implement `math.NthPrime` function"
    topic: "00-introduction"
    score: 2
  - name: "vector"
    description: "Implement `vector` package"
    topic: "01-data-structures"
    score: 6
  - name: "matrix"
    description: "Implement `matrix` package"
    topic: "01-data-structures"
    score: 2
  - name: "ndarray"
    description: "Implement `ndarray` package"
    topic: "01-data-structures"
    score: 2
  - name: "maxqueue"
    description: "Implement `maxqueue` package"
    topic: "01-data-structures"
    score: 2
  - name: "nthelement"
    description: "Implement `pick.NthElement` function"
    topic: "02-sorting"
    score: 3
  - name: "firstn"
    description: "Implement `pick.FirstN` function"
    topic: "02-sorting"
    score: 4
