tests:
  - name: "cmp"
    description: "`cmp.Min` and `cmp.Max`"
    topic: "00-introduction"
    score: 0
  - name: "primes"
    description: "`math.NthPrime` function"
    topic: "00-introduction"
    score: 2
  - name: "vector"
    description: "`vector` package"
    topic: "01-data-structures"
    score: 6
  - name: "matrix"
    description: "`matrix` package"
    topic: "01-data-structures"
    score: 2
  - name: "ndarray"
    description: "`ndarray` package"
    topic: "01-data-structures"
    score: 2
  - name: "maxqueue"
    description: "`maxqueue` package"
    topic: "01-data-structures"
    score: 2
  - name: "nthelement"
    description: "`pick.NthElement` function"
    topic: "02-sorting"
    score: 3
  - name: "firstn"
    description: "`pick.FirstN` function"
    topic: "02-sorting"
    score: 4
  - name: "radix"
    description: "`radix` package"
    topic: "02-sorting"
    score: 3
  - name: "listsort"
    description: "`xlist.Sort` function"
    topic: "02-sorting"
    score: 4
  - name: "lru"
    description: "`lru` package"
    topic: "04-hashing"
    score: 2
  - name: "treebalanced"
    description: "`tree.NewBST` function"
    topic: "03-trees"
    score: 2
  - name: "treeinorder"
    description: "`tree.InOrder` function"
    topic: "03-trees"
    score: 2
  - name: "treeserialise"
    description: "`tree.Decode` and `tree.Tree.Encode` functions"
    topic: "03-trees"
    score: 3
  - name: "treesym"
    description: "`tree.Tree.IsSym` function"
    topic: "03-trees"
    score: 2
  - name: "bitset"
    description: "`bitset` package"
    topic: "05-sets"
    score: 4
