repos:
- repo: git://github.com/mkuznets/stdlib-linter
  rev: v0.4.0
  hooks:
    - id: generate
    - id: gofmt
    - id: stdlib-linter
      args: [-c=./linter_config.yaml, ./stdlib]
    - id: no-untracked
