goroutines_banned: true
packages:
  - errors
  - fmt
  - strings
  - strconv
  - math
  - math/rand
  - math/bits
  - sort
  - container/heap
  - container/list
package_prefixes:
  - hsecode.com/stdlib
banned_ids:
banned_calls:
  "*":
    - println
    - print
    - recover
  vector:
    - append
