// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package matrix

// int is a generic type for Matrix values (imported from github.com/cheekybits/genny/generic).
//
// The package contains subpackages where int is automatically replaced with concrete types.
//
// The int subpackage is required for tests. Make sure to include the following comment in your source code:
//
// //go:generate genny -in=$GOFILE -out=int/dont_edit.go gen "Int=int"

// Matrix implements row-major 2D array of int
type Matrix struct {
	values []int
	Rows   int // number of rows
	Cols   int // number of columns
}

// New creates a new Matrix with n rows and m columns
func New(n, m int) *Matrix {
	mat := new(Matrix)
	mat.values = make([]int, n*m)
	mat.Rows, mat.Cols = n, m
	return mat
}

func (M *Matrix) idx(i, j int) int {
	if i >= M.Rows || i < 0 || j >= M.Cols || j < 0 {
		panic("out-of-range")
	}
	return M.Cols*i + j
}

// Get returns a matrix element by indices (i, j). Panics if the indices are out of range.
func (M *Matrix) Get(i, j int) int {
	return M.values[M.idx(i, j)]
}

// Set assigns a value of matrix element by indices (i, j). Panics if the indices are out of range.
func (M *Matrix) Set(i, j int, v int) {
	M.values[M.idx(i, j)] = v
}
