tests:
  - cmp
  - primes
  - vector
  - matrix
  - ndarray
  - maxqueue
  - nthelement
  - firstn
  - radix
  - listsort
  - treebalanced
  - treeinorder
  - treeserialise
  - treesym
  - treenoleft
  - treeancestry
  - lru
  - set
  - bitset
  - islands
  - graph
  - tsort
  - mst
  - dijkstra
  - levenshtein
  - lcs
  - segmentation
  - fulltext
