tests:
  - cmp
  - primes
  - vector
  - matrix
  - ndarray
  - maxqueue
  - nthelement
  - firstn
  - radix
  - listsort
  - treebalanced
  - treeinorder
  - treeserialise
  - treesym
  - treenoleft
  - treeancestry
  - lru
  - bitset
  - islands
  - graph
  - graphtsort
  - graphmst
